name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PUB_KEY: '${{ secrets.PUB_KEY }}'

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USER}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            docker build --build-arg "PUB_KEY=$PUB_KEY" . -f Dockerfile -t larrxi/ssh-server:latest -t larrxi/ssh-server:$(git rev-parse --short HEAD)
        - name: push the docker image
          id: push-docker-image
          run: docker push larrxi/ssh-server:$(git rev-parse --short HEAD)
